
version: '3'

services:
  local_instance_3306:
    image: mysql:8.0.18
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ThemeDb
    ports:
      - "3306:3306"
  app:
    build: .
    ports:
        - "5001:80"
    depends_on:
        - local_instance_3306
